version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: tripuser
      POSTGRES_PASSWORD: tripsecret
      POSTGRES_DB: tripdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
